site_name: BitCurator Docs
site_url: 
nav:
  - BitCurator Documentation:
    - Home : 'index.md'
    - 'About/Original Project Diagrams.md'
    - 'About/Support and Past Funding.md'
  - Installation:
    - Overview : 'Installing BitCurator/Installing BitCurator.md'
    - 'Installing BitCurator/Install Option 1: Installation via Dedicated Machine.md'
    - 'Installing BitCurator/Install Option 2: Installation via Virtual Machine.md'
    - Using Active Directory : 'Installing BitCurator/Configuring BitCurator to enable users to authenticate with Active Directory accounts.md'
    - 'Installing BitCurator/Internationalization and Ubuntu.md'
    - 'Installing BitCurator/Migrating BitCurator VirtualBox VM to Hyper-V.md'
  - Guides: 
    - 'All Step-by-Step Guides/Working in the BitCurator Environment.md'
    - 'All Step-by-Step Guides/Imaging and Recovery Guides.md'
    - 'All Step-by-Step Guides/Forensics and Reporting Guides.md'
    - 'All Step-by-Step Guides/Packaging and Transfer Guides.md'
  - Additional Resources:
    - 'Tools.md'
    - 'Troubleshooting and FAQ.md'
    - 'Resources.md'
  - Walkthrough: 
    - Overview: 'BitCurator Walkthrough/BitCurator Walkthrough.md'
  - About:    
    - 'About/Original Project Diagrams.md'
    - 'About/Support and Past Funding.md'


theme: readthedocs
